### ISSUE TITLE
World and World_1M crash the app.

### ISSUE THREAD

**Issue by phbrbr** [theworldisnotflat/shriveling_world#127]
**Describe the bug**
When selecting World or World_1M data the app doesn't work anymore. The page needs to be reloaded.

On macOS Catalina (Version 10.15.7):
- In Safari 14 console log:
 `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'w[t].speed')`
- In Firefox 81 console log:
 `Uncaught (in promise) TypeError: w[t] is undefined`

**To Reproduce**
1. Click on 'World' or 'World_1M'
2. Open Console
3. See error

**Expected behavior**
Error management, for example display an alert for the user ( _imported dataset is corrupted_ ,  _something went wrong_ or anything useful). It should not crash the app.

**Comment by theworldisnotflat** [comment]
china Taiwan 1M: cone yea: 1964-2014 toujours la valeur 1.4639 pour alpha
Europe 1M: idem
Germany 22: 1964-2014 alpha: 1.3959
Japan: 1964 Alpha=1.437    1980 Alpha=1.504 jusqu'en 2004 puis 2014 Alpha=1.437

Dates are taken from the 'network' file: starting date in column yearBegin and ending year in column yearEnd

**Comment by theworldisnotflat** [comment]
Solved by @saamus , well done :)
