### ISSUE TITLE
Possibility to deselect non road speed slope for cones

### ISSUE THREAD

**Issue by theworldisnotflat** [theworldisnotflat/shriveling_world#138]
**Is your feature request related to a problem? Please describe.**
Need to deselect the current default mode, because currently China and Germany models have cones with non road slopes, based in HST networks (i.e. cones with different slopes) which should be an option and not default. It should be possible to select the option of having only cones with one single slope, the slope of road transport.

**Describe the solution you'd like**
Make it as an option a checkbox in the UI

**Describe alternatives you've considered**
not workaround

**Comment by alainlhostis** [comment]
solved
