### ISSUE TITLE
THREE.WebGLRenderer 98 error

### ISSUE THREAD

**Issue by Bakaniko** [theworldisnotflat/shriveling_world#29]
Hi, 

I tried this project into a Ubuntu 18.04 virtual machine with Chromium and Firefox web browsers.

It didn't worked as expected.  Symptoms were : 
- Chromium 71.03578 : Interface present, white background, calcul de FPS (between 5 and 15)
- Firefox 64.0 : no interface, black background, FPS window present but inactive

The capture below show the firefox example:

![image](https://user-images.githubusercontent.com/17683898/51251611-01f4f700-199a-11e9-8c58-00b10041b14c.png)

Both browsers display a THREE.WebGLRenderer 98 error. Firefox gives us more context.

Thanks,

Nicolas

**Comment by Bakaniko** [comment]
This is the commands I used on a fresh ubuntu MATE 18.04 install:

```bash
sudo apt update 
sudo apt install chromium-browser
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install -y nodejs
nvm install node
npm --help
cd Documents/shriveling_world/
npm i
gulp
sudo npm install gulp -g
gulp
gulp server
```

I didn't install nvm as I didn't know what it is its purpose...

**Comment by CodeInLight** [comment]
> I didn't install nvm as I didn't know what it is its purpose...
I think it is a writting mistake, I think it s npm.

In my Unbuntu 18.04 : 


In order to check version and update if needed : 
`node -v
npm -v 
npm install -g npm@next
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo npm i
gulp
gulp server
`  
It works for me with these commande lines

**Comment by Bakaniko** [comment]
Hi @CodeInLight 

Thanks for the indications, I'll try that today. :)

**Comment by theworldisnotflat** [comment]
Hi @CodeInLight thanks for you swift fix proposal !
I tried on my office ubuntu 16.04 machine; I am not admin there :(
I executed the instructions you gave without `sudo`, except the line `n stable` which was not recognised as a known command.
It would be nice to stabilise a list of instructions valid for a non admin, hoping it is possible
In the end the result is the same,  unfortunately, no processing of the files other than the shapefile

**Comment by Bakaniko** [comment]
I tried several things this morning.

On Ubuntu 18.04 VM:
I tried the commands provided by @CodeInLight , without any progress. I get the exact same thing.

On Windows 10:
After losing sometimes to install and configure node/npm, I was able to install everything execpt the "n" module (it is not available for win32 env):

```bash
$ npm install -g n
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@2.1.12: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

As I didn't using on my test before today, I tried without n.
I had no issues with `npm i` and `gulp server`

But the page is not working. I got this error:
```js
// Chromium
GET http://localhost:8080/javascript/shriveling.js net::ERR_ABORTED 404 (Not Found)
(index):24 Uncaught ReferenceError: shriveling is not defined
    at (index):24
```

```js
//Firefox
Échec du chargement pour l’élément <script> dont la source est « http://localhost:8080/javascript/shriveling.js ». localhost:8080:21:1
ReferenceError: shriveling is not defined[En savoir plus]
```

So it doesn't find `shriveling.js` in the javascript folder.

Is it because of the missing `n` module ? (I don't think so)
Where is that `shriveling.js` ?

I'm at commit https://github.com/theworldisnotflat/shriveling_world/commit/3e1684bb26b9b8edcaa93f1de663d3f578114f22

**Comment by CodeInLight** [comment]
You need to run the command : gulp 
before running : gulp server

The gulp command will generate the shriveling.js file.

**Comment by theworldisnotflat** [comment]
I have added the `n` module successfully in Ubuntu but with no better result (`npm install -g n`)

**Comment by CodeInLight** [comment]
Do you have any issue after running 'gulp'?

**Comment by theworldisnotflat** [comment]
now it worked!! in Firefox 
I will summarise the instructions in a new virtual machine

**Comment by Bakaniko** [comment]
@CodeInLight Yes I forgot to call gulp after installing it.
Now I got an error from gulp:

```bash
$ gulp
[13:43:52] Using gulpfile D:\Roelandt\PROJETS\InProgress\LVMT\Shrivelling_World\shriveling_world\gulpfile.js
[13:43:52] Starting 'default'...
[13:43:52] Starting 'clean'...
[13:43:52] Starting '<anonymous>'...
[13:43:52] Finished 'clean' after 9.3 ms
'tslint' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
[13:43:52] '<anonymous>' errored after 47 ms
[13:43:52] Error in plugin "gulp-shell"
Message:
    Command `tslint -c tslint.json -e src/webWorkers/**/*.ts src/**/**/*.ts src/*.ts` failed with exit code 1
[13:43:52] 'default' errored after 50 ms
```

This my bash history:

```bash
   20  npm -v
   21  node -v
   22  cd LVMT/Shrivelling_World/shriveling_world/
   23  npm install -g npm@next
   24  npm2 install npm@latest -g
   25  npm install -g npm@next
   26  npm2 install npm@latest -g
   27  npm -v
   28  sudo npm cache clean -f
   29  npm cache clean -f
   30  npm install -g n
   31  npm i
   32  gulp
   33  npm install gulp -g
   34  gulp server
   35  git status
   36  gulp server
   37  gulp
   38  gulp server
   39  history
   40  npm i tslint
   41  gulp
   42  history
```

**Comment by Bakaniko** [comment]
I commented the following lines in [gulpfile.js](https://github.com/theworldisnotflat/shriveling_world/blob/master/gulpfile.js):

* [#189](https://github.com/theworldisnotflat/shriveling_world/blob/master/gulpfile.js#L189)
* [#210](https://github.com/theworldisnotflat/shriveling_world/blob/master/gulpfile.js#L210)

And I changed [#200](https://github.com/theworldisnotflat/shriveling_world/blob/master/gulpfile.js#L200) so the tslint task won't be called

So gulp compiled and I was able to launch the application.

With chromium and Firefox, I got the interface, the lands and the arcs showing but not the cones.
So it is not perfect but there is some progress.

**Comment by Bakaniko** [comment]
I runned the application 
(still without tslint)

at startup (without data) I get this error:
```js
THREE.WebGLRenderer 98 shriveling.js:2:283047
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:2:304978
```

When I load the first file ([110m_land_shrivel_v03.geojson](https://github.com/theworldisnotflat/shriveling_world/blob/master/example/datas/to_drop_in_app_sample/110m_land_shrivel_v03.geojson)), the lands are displayed and the console show the following errors:
```js
THREE.WebGLRenderer 98 shriveling.js:2:283047
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:2:304978
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:18:39153
```

Then I load the other files without errors at the exception of the last one ([transport_network_v06.csv](https://github.com/theworldisnotflat/shriveling_world/blob/master/example/datas/to_drop_in_app_sample/transport_network_v06.csv)):
```
THREE.WebGLRenderer 98 shriveling.js:2:283047
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:2:304978
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:18:39153
444 26 shriveling.js:18:43889
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:18:39153
Error: WebGL warning: drawElements: TEXTURE_2D at unit 7 is of type FLOAT, but the shader samples as INT. shriveling.js:1:47356
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. shriveling.js:18:39153
```

I think that the line `Error: WebGL warning: drawElements: TEXTURE_2D at unit 7 is of type FLOAT, but the shader samples as INT.` is the error who block the cones display.

For the line `444 26`, I think it is a console.log forgotten somewhere. Maybe the calculated arcs and nodes ?

**Comment by CodeInLight** [comment]
Going without tslint may be not the right solution... I remember i had the same issue at the begining. Do you use visual Code as EDI?

1) try to reactivate tslint and enter the cmd :                `**gulp build**`
2) use `npm i -g tslint` instead of `npm i tslint` and the same for `npm i`  use `npm -g i` 
3) if this doesn't work verify your NODE_PATH ; In my case I added explicitely : `export NODE_PATH=./node_modules`
4) finally try with                  `**gulp**`

**Comment by theworldisnotflat** [comment]
strange: on my laptop, have installed `n` 
works fine in Chromium but in Firefox 64.0 everything is visible except cones :(

**Comment by theworldisnotflat** [comment]
On a fresh new virtual machine Ubuntu 18.04
I did
```
sudo apt update 
sudo apt install chromium-browser
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install node
npm --help
sudo npm install -g npm@next
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo apt install git
cd Documents
git clone https://github.com/theworldisnotflat/shriveling_world.git
cd shriveling_world/
npm i
sudo npm install gulp -g
gulp
gulp server
```

et ça a marché!!
