### ISSUE TITLE
Lacks of CONTRIBUTING.md and Licence.md

### ISSUE THREAD

**Issue by Bakaniko** [theworldisnotflat/shriveling_world#35]
I think, in order to prepare for opening this code, that this project should provide some files to provide informations to newcomers :

- [x] LICENCE.md with the  choosen license text
- [x] CONTRIBUTING.md : how people can contribute to the code
- [x] CONTRIBUTORS.txt : list of contributors
- [x] Code of conduct (optional but needed if the community starts to grow)

There is more information provided on  the [opensource.guide/how-to-contribute page](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project).

To help to choose a the license, there are several ressources:
- [the dedicated datagouf.fr page](https://www.data.gouv.fr/fr/licences)
- [legifrance](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000034504991&cidTexte=LEGITEXT000031366350&dateTexte=29991231)

There is also a template for the CONTRIBUTING.md file:
- [Good-CONTRIBUTING.md-template.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by theworldisnotflat** [comment]
Done, thank you @Bakaniko !
