### ISSUE TITLE
'year' UI does not function

### ISSUE THREAD

**Issue by theworldisnotflat** [theworldisnotflat/shriveling_world#38]
'year' UI does not function

**Comment by CodeInLight** [comment]
Yes I think years never worked, moreover when I changed the default year which is 2010, LineMeshColleciton did not appears. So only 2010 works.

**Comment by theworldisnotflat** [comment]
I did worked very perfectly well, I assure you, can't tell when it stopped working though

**Comment by kaktus40** [comment]
see [here](https://github.com/dataarts/dat.gui/issues/48). It's linked to dat.GUI issue. It seems a PR should resolve it.

**Comment by theworldisnotflat** [comment]
Farouk provided a workaound, to be used untill the issue is solved: from the console type: `shriveling.configuration.year=1980` for the year 1980

**Comment by kaktus40** [comment]
maybe we should use [controlKit](https://github.com/automat/controlkit.js) instead of dat.GUI?

**Comment by CodeInLight** [comment]
It is a good idea we can try i think

**Comment by theworldisnotflat** [comment]
solved by PR #71
