### ISSUE TITLE
Commenting the code

### ISSUE THREAD

**Issue by theworldisnotflat** [theworldisnotflat/shriveling_world#46]
- [x] @kaktus40 implements automatic doc generation
- [x] equations and figures should be stored in a stable URL and referred to in the documentation; equations and figures are in the annex of IEEE article
- [x] this issue is a long running effort to document the code to allow for a future more open development

**Comment by kaktus40** [comment]
You should respect the API describe in [typedoc](https://typedoc.org/guides/doccomments/)

**Comment by theworldisnotflat** [comment]
well engaged
