### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by theworldisnotflat** [theworldisnotflat/shriveling_world#48]
I feel 'shriveling world' is not the best idea to name the project, I wish we could find a better name!

**Comment by theworldisnotflat** [comment]
Please propose new ideas!
I thought this morning to "GeoTimeSpace" this is slightly abusive because spring maps are also a time-space but hey miss the surface, so they are a "time-spaced" graph

**Comment by CodeInLight** [comment]
GeoTimeSpace is not so bad 👍
I don't have much ideas 😅

**Comment by theworldisnotflat** [comment]
let's keep the 'shriveling' word to express the transformation of geographical space, as @phbrbr observed, words to describe an image must be considered with great attention!
